import AppKit

// Polls NSPasteboard.changeCount every 500ms on a background queue.
// On change, classifies the contents (file URLs → image → text) and
// hands off to ClipStore. Privacy gate skips any content tagged as
// concealed/transient/auto-generated (1Password, password managers, etc).

final class ClipboardWatcher {
    private let store: ClipStore
    private let queue = DispatchQueue(label: "pastique.watcher", qos: .utility)
    private var timer: DispatchSourceTimer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    // Signature + timestamp of the last clip we *actually inserted*.
    // Pasteboard changeCount bumps even when content is unchanged
    // (Universal Clipboard re-syncs, Safari focus events). Those phantom
    // re-writes typically arrive within one polling tick of the original,
    // so we only suppress duplicates for a window just longer than the
    // 500ms tick interval. Anything ≥`dedupWindow` apart is treated as a
    // deliberate re-copy and bubbles the entry to the top.
    private var lastSignature: String?
    private var lastSignatureAt: TimeInterval = 0
    private let dedupWindow: TimeInterval = 0.6

    private func isPhantomDuplicate(_ sig: String) -> Bool {
        sig == lastSignature
            && (Date().timeIntervalSince1970 - lastSignatureAt) < dedupWindow
    }

    private func recordSignature(_ sig: String) {
        lastSignature = sig
        lastSignatureAt = Date().timeIntervalSince1970
    }

    static let concealedUTIs: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // Some password managers use this proprietary type:
        "com.agilebits.onepassword",
    ]

    /// Pure predicate: should this pasteboard content be skipped because
    /// the source marked it as sensitive/transient? Exposed for tests so
    /// the privacy guarantee can be exercised without a real NSPasteboard.
    static func shouldSkip(pasteboardTypes: Set<String>) -> Bool {
        !pasteboardTypes.isDisjoint(with: concealedUTIs)
    }

    init(store: ClipStore) {
        self.store = store
    }

    func start() {
        let t = DispatchSource.makeTimerSource(queue: queue)
        t.schedule(deadline: .now() + .milliseconds(500),
                   repeating: .milliseconds(500),
                   leeway: .milliseconds(50))
        t.setEventHandler { [weak self] in self?.tick() }
        t.resume()
        timer = t
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    // Call after we ourselves write to the pasteboard (paste-back from the
    // picker). Bumps the watermark to the current changeCount so the next
    // tick doesn't re-insert what we just wrote.
    func acknowledgeOwnWrite() {
        let cc = NSPasteboard.general.changeCount
        queue.async { [weak self] in
            guard let self else { return }
            if cc > self.lastChangeCount { self.lastChangeCount = cc }
        }
    }

    private func tick() {
        let pb = NSPasteboard.general
        let cc = pb.changeCount
        guard cc != lastChangeCount else { return }
        lastChangeCount = cc

        // Privacy gate
        let types = Set((pb.types ?? []).map(\.rawValue))
        if Self.shouldSkip(pasteboardTypes: types) { return }

        do {
            // 1. File URLs (Finder copy → file)
            if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL],
               !urls.isEmpty,
               urls.allSatisfy({ $0.isFileURL }) {
                let sig = "file:" + urls.map { $0.absoluteString }.joined(separator: "|")
                if isPhantomDuplicate(sig) { return }
                try store.insertFileURLs(urls)
                recordSignature(sig)
                return
            }

            // 2. Images. Prefer PNG; fall back to TIFF and re-encode.
            if let png = pb.data(forType: .png) {
                let sig = "img:png:\(png.count):\(png.hashValue)"
                if isPhantomDuplicate(sig) { return }
                try store.insertImage(pngData: png)
                recordSignature(sig)
                return
            }
            if let tiff = pb.data(forType: .tiff),
               let img = NSImage(data: tiff),
               let bitmap = bitmapRep(from: img),
               let pngData = bitmap.representation(using: .png, properties: [:]) {
                let sig = "img:tiff:\(tiff.count):\(tiff.hashValue)"
                if isPhantomDuplicate(sig) { return }
                try store.insertImage(pngData: pngData)
                recordSignature(sig)
                return
            }

            // 3. Plain text (with optional rich UTI payloads if richMode is on)
            if let s = pb.string(forType: .string), !s.isEmpty {
                let sig = "text:\(s)"
                if isPhantomDuplicate(sig) { return }
                let extras = Settings.richMode ? Self.richPayloads(from: pb) : []
                try store.insertText(s, extraPayloads: extras)
                recordSignature(sig)
                return
            }
        } catch {
            NSLog("Pastique: insert failed: %@", "\(error)")
        }
    }

    private func bitmapRep(from image: NSImage) -> NSBitmapImageRep? {
        if let tiff = image.tiffRepresentation {
            return NSBitmapImageRep(data: tiff)
        }
        return nil
    }

    // UTIs we capture in rich mode alongside plain text. RTF and HTML are
    // the common cases (Pages, web pages, Notes). RTFD variants cover
    // documents with embedded images.
    private static let richTextUTIs: Set<String> = [
        "public.rtf",
        "public.html",
        "public.rtfd",
        "com.apple.flat-rtfd",
    ]

    private static func richPayloads(from pb: NSPasteboard) -> [(uti: String, data: Data)] {
        var result: [(uti: String, data: Data)] = []
        for type in (pb.types ?? []) {
            if richTextUTIs.contains(type.rawValue),
               let data = pb.data(forType: type) {
                result.append((type.rawValue, data))
            }
        }
        return result
    }
}
